trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: github  # Grupo que contém github.username e github.token

stages:
  - stage: SyncToGitHub
    displayName: 'Sync Azure master to GitHub portfolio'
    jobs:
      - job: PushToGitHub
        steps:
          - checkout: self
            clean: true
            persistCredentials: true

          - script: |
              echo "🔧 Configurando Git"
              git config --global user.name "Pedro Vinícios"
              git config --global user.email "pedrooviniciossantos@gmail.com"

              echo "🔍 Branch atual:"
              git branch

              echo "➕ Adicionando remoto GitHub"
              git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/PedroVinicioss/MeuDiagnostico.git

              echo "⬆️ Dando push da branch atual para o GitHub"
              git push github HEAD:main --force
            env:
              GITHUB_USERNAME: $(github.username)
              GITHUB_TOKEN: $(github.token)