trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: github

stages:
  - stage: SyncToGitHub
    displayName: 'Sync Azure master to GitHub portfolio'
    jobs:
      - job: PushToGitHub
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
            fetchDepth: 0  # necessário para ter acesso aos refs completos

          - script: |
              echo "🔧 Configurando Git"
              git config --global user.name "Pedro Vinícios"
              git config --global user.email "pedrooviniciossantos@gmail.com"

              echo "🔍 Criando branch local 'master' a partir de origin/master"
              git checkout -b master origin/master

              echo "📌 Verificando refs locais"
              git show-ref

              echo "➕ Adicionando remoto GitHub"
              git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/PedroVinicioss/MeuDiagnostico.git

              echo "⬆️ Dando push da branch master para main no GitHub"
              git push github refs/heads/master:refs/heads/main --force
            env:
              GITHUB_USERNAME: $(github.username)
              GITHUB_TOKEN: $(github.token)
